version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - checkout

      - run: mkdir -p /tmp/build

      - run: cp -r build /tmp

      - run: ls -la /tmp/build

      - persist_to_workspace:
          root: /tmp
          paths:
            - build/*

  deploy-auto:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - attach_workspace:
          at: /tmp

      - run: ls -la /tmp/build

      - run:
          name: Deploy auto environment to Netlify
          command: npx netlify-cli deploy -p --dir=/tmp/build --site=$NETLIFY_AUTOENV_SITE_ID --auth=$NETLIFY_AUTH_TOKEN

  smoke-test-auto:
    docker:
      - image: buildpack-deps:trusty

    environment:
      NETLIFY_APP_NAME: 'yq-auto-introspection-app'

    steps:
      - run:
          name: Smoke test for auto environment
          command: curl --fail https://$NETLIFY_APP_NAME.netlify.com

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-auto:
          requires:
            - build
      - smoke-test-auto:
          requires:
            - deploy-auto
