version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - run: mkdir -p /tmp/build

      - run: cp -r build /tmp

      - run: ls -la /tmp/build

      - persist_to_workspace:
          root: /tmp
          paths:
            - build/*

  deploy-auto:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - attach_workspace:
          at: /tmp

      - run: ls -la /tmp/build

      - run:
          name: Deploy auto environment to Netlify
          command: npx netlify-cli deploy -p --dir=/tmp/build --site=$NETLIFY_AUTOENV_SITE_ID --auth=$NETLIFY_AUTH_TOKEN

  smoke-test-auto:
    docker:
      - image: buildpack-deps:trusty

    environment:
      NETLIFY_APP_NAME: 'yq-auto-introspection-app'

    steps:
      - run:
          name: Smoke test for auto environment
          command: curl --fail https://$NETLIFY_APP_NAME.netlify.com

  deploy-test:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - attach_workspace:
          at: /tmp

      - run: ls -la /tmp/build

      - run:
          name: Deploy auto environment to Netlify
          command: npx netlify-cli deploy -p --dir=/tmp/build --site=$NETLIFY_TESTENV_SITE_ID --auth=$NETLIFY_AUTH_TOKEN

  smoke-test-test:
    docker:
      - image: buildpack-deps:trusty

    environment:
      NETLIFY_APP_NAME: 'yq-test-introspection-app'

    steps:
      - run:
          name: Smoke test for auto environment
          command: curl --fail https://$NETLIFY_APP_NAME.netlify.com

  deploy-staging:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - attach_workspace:
          at: /tmp

      - run: ls -la /tmp/build

      - run:
          name: Deploy auto environment to Netlify
          command: npx netlify-cli deploy -p --dir=/tmp/build --site=$NETLIFY_STAGINGENV_SITE_ID --auth=$NETLIFY_AUTH_TOKEN

  smoke-test-staging:
    docker:
      - image: buildpack-deps:trusty

    environment:
      NETLIFY_APP_NAME: 'yq-staging-introspection-app'

    steps:
      - run:
          name: Smoke test for auto environment
          command: curl --fail https://$NETLIFY_APP_NAME.netlify.com

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-auto:
          requires:
            - build
      - smoke-test-auto:
          requires:
            - deploy-auto
      - hold:
          type: approval
          requires:
            - deploy-auto
      - deploy-test:
          requires:
            - hold
      - smoke-test-test:
          requires:
            - deploy-test
      - hold-staging:
          type: approval
          requires:
            - deploy-test
      - deploy-staging:
          requires:
            - hold-staging
      - smoke-test-staging:
          requires:
            - deploy-staging
