version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

      - run: npm run build

  deploy-auto:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - checkout
      - run:
          name: Deploy auto environment to Netlify
          command: npm run netlify:deploy:auto

  smoke-test-auto:
    docker:
      - image: buildpack-deps:trusty
    environment:
      NETLIFY_APP_NAME: 'yq-auto-introspection-app'
    steps:
      - run:
          name: Smoke test for auto environment
          command: curl --fail https://$NETLIFY_APP_NAME.netlify.com

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-auto:
          requires:
            - build
      - smoke-test-auto:
          requires:
            - deploy-auto
